version: '3.8'

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      # путь локальной папки бд
      - ./databases/mysql57:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 5000:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - internal

  server:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: ./Dockerfile
    image: movie-server
    restart: unless-stopped
    command: npx sequelize-cli db:seed:all
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${MYSQL_DOCKER_PORT}
    stdin_open: true
    tty: true
    networks:
      - internal

  app:
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./src/app/Dockerfile
    image: movie-app
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - internal

volumes:
  db:

networks:
  internal: